theme: jekyll-theme-cayman

title: ¡Travel with Spanish!
github:
  spain: spain.html
  traveladventures: traveladventures.html
  southamerica: southamerica.html
  learnspanish: learnspanish.html
  resources: resources.html
