theme: jekyll-theme-cayman

title: ¡Travel with Spanish!
github:
  spain: spain.html
  traveladventures: traveladventures.html
  southamerica: southamerica.html
  learnspanish: learnspanish.html
  learnspanish2: learnspanish2.html
  learnspanish3: learnspanish3.html
  learnspanish4: learnspanish4.html
  resources: resources.html
